// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: game.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope 是每一帧(length-prefixed frame)的 body。
// 所有消息都包在 Envelope 里,用 oneof 区分类型:解一次码就能 switch 分发,
// 帧头不用再放 msg_type。取舍见 docs/DECISIONS.md D1。
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 请求方自增的序号。应答原样带回,发送方靠它把请求和应答配对。
	// 服务端主动推送的消息(广播、踢人)seq 为 0。
	Seq uint32 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// 字段号按模块分段,新消息往对应区间里加:
	//   10–19 网关(心跳)   20–29 登录   30–39 房间   40–49 同步(Lab 4)
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Ping
	//	*Envelope_Pong
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Ping struct {
	Ping *Ping `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong *Pong `protobuf:"bytes,11,opt,name=pong,proto3,oneof"`
}

func (*Envelope_Ping) isEnvelope_Payload() {}

func (*Envelope_Pong) isEnvelope_Payload() {}

// Ping 兼作心跳:客户端定期发;服务端在 idle timeout 内收不到任何帧就踢人。
type Ping struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 客户端发送时刻(unix ms)。Pong 原样带回,客户端不用保存状态就能算 RTT。
	ClientTimeMs  int64 `protobuf:"varint,1,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *Ping) GetClientTimeMs() int64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTimeMs  int64                  `protobuf:"varint,1,opt,name=client_time_ms,json=clientTimeMs,proto3" json:"client_time_ms,omitempty"` // 从 Ping 原样复制
	ServerTimeMs  int64                  `protobuf:"varint,2,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"` // 服务端处理时刻(unix ms),以后可以用来估算时钟偏差
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *Pong) GetClientTimeMs() int64 {
	if x != nil {
		return x.ClientTimeMs
	}
	return 0
}

func (x *Pong) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\"k\n" +
	"\bEnvelope\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\rR\x03seq\x12 \n" +
	"\x04ping\x18\n" +
	" \x01(\v2\n" +
	".game.PingH\x00R\x04ping\x12 \n" +
	"\x04pong\x18\v \x01(\v2\n" +
	".game.PongH\x00R\x04pongB\t\n" +
	"\apayload\",\n" +
	"\x04Ping\x12$\n" +
	"\x0eclient_time_ms\x18\x01 \x01(\x03R\fclientTimeMs\"R\n" +
	"\x04Pong\x12$\n" +
	"\x0eclient_time_ms\x18\x01 \x01(\x03R\fclientTimeMs\x12$\n" +
	"\x0eserver_time_ms\x18\x02 \x01(\x03R\fserverTimeMsB7Z5github.com/Anthonyz5527083/game-server/internal/pb;pbb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_game_proto_goTypes = []any{
	(*Envelope)(nil), // 0: game.Envelope
	(*Ping)(nil),     // 1: game.Ping
	(*Pong)(nil),     // 2: game.Pong
}
var file_game_proto_depIdxs = []int32{
	1, // 0: game.Envelope.ping:type_name -> game.Ping
	2, // 1: game.Envelope.pong:type_name -> game.Pong
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_game_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Ping)(nil),
		(*Envelope_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
